Repository PharmaTechVe/ecommerce, pull requests merged in 2025-04, with the labels that each got.

#38 Fix: Product Detail
  src/app/product/[productId]/presentation/[presentationId]/page.tsx
Labels: bug

#37 feature: add email-validation view
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/app/register/RegisterForm.tsx
  src/components/EmailValidation.tsx
  src/components/Navbar.tsx
Labels: feature

#40 HotFix Login API Instance and Warnings
  src/app/login/LoginForm.tsx
  src/app/page.tsx
  src/app/register/RegisterForm.tsx
Labels: bug

#42 Fixing API Instances
  package.json
  src/app/page.tsx
  src/app/register/RegisterForm.tsx
  src/components/EmailValidation.tsx
  src/lib/sdkConfig.ts
Labels: bug

#44 features/ECOM/user-profile
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/user/address/[id]/edit/page.tsx
  src/app/user/address/new/page.tsx
  src/app/user/address/page.tsx
  src/app/user/layout.tsx
  src/app/user/page.tsx
  src/app/user/security/recover-password/page.tsx
  src/app/user/security/update-password/page.tsx
  src/components/Avatar.tsx
  src/components/Breadcrumb.tsx
  src/components/Calendar.tsx
  src/components/Dropdown.tsx
  src/components/GoogleMap/GoogleMap.tsx
  src/components/GoogleMap/UserAddressPopup.tsx
  src/components/Input/Input.tsx
  src/components/Navbar.tsx
  src/components/RadioButton.tsx
  src/components/SideBar.tsx
  src/components/User/EnterCodeForm.tsx
  src/components/User/ProfileLayout.tsx
  src/components/User/UserAddressForm.tsx
  src/components/User/UserBreadCrumbs.tsx
  src/components/User/UserPasswordForm.tsx
  src/components/User/UserProfileForm.tsx
  src/lib/utils/constants/DateUtils.ts
  src/lib/utils/helpers/parsePlaceFromSearchBox.ts
  src/lib/validations/registerSchema.ts
  src/lib/validations/updatePasswordSchema.ts
  src/lib/validations/userAddressSchema.ts
  src/styles/globals.css
  src/styles/styles.ts
Labels: feature

#49 feature : Add product search filters, suggestions, and results page
  next.config.ts
  package-lock.json
  package.json
  src/app/search/page.tsx
  src/components/SearchBar.tsx
  src/components/SidebarFilter.tsx
  src/components/SuggestionProduct.tsx
Labels: feature

#48 Features/ecom/user profile orders
  next.config.ts
  package-lock.json
  package.json
  src/app/product/[productId]/presentation/[presentationId]/page.tsx
  src/app/search/page.tsx
  src/app/user/address/[id]/edit/page.tsx
  src/app/user/address/page.tsx
  src/app/user/layout.tsx
  src/app/user/order/[id]/detail/page.tsx
  src/app/user/order/page.tsx
  src/app/user/page.tsx
  src/components/Badge.tsx
  src/components/CheckButton.tsx
  src/components/GoogleMap/GoogleMap.tsx
  src/components/GoogleMap/UserAddressPopup.tsx
  src/components/Pagination.tsx
  src/components/Product/ProductBranch.tsx
  src/components/SideBar.tsx
  src/components/User/Order/UserOrderDetail.tsx
  src/components/User/Order/UserOrdertable.tsx
  src/components/User/UserBreadCrumbs.tsx
  src/components/User/UserProfileForm.tsx
  src/lib/utils/helpers/googleMapsConfig.ts
  src/pages/api/sign-cloudinary.ts
  src/styles/styles.ts
Labels: feature

#51 Fix: Spacing and Layout Adjustments for Product Cards and Carousel
  src/app/page.tsx
  src/app/search/page.tsx
  src/app/user/address/[id]/edit/page.tsx
  src/app/user/address/page.tsx
  src/components/Product/CardBase.tsx
  src/components/Product/ProductCard.tsx
  src/components/Product/ProductCarousel.tsx
Labels: bug

#47 WIP feat(checkout): start building checkout flow with coupon input and scrollable summary
  src/app/checkout/CheckoutContext.tsx
  src/app/checkout/OrderSummary.tsx
  src/app/checkout/[step]/DeliveryInfo.tsx
  src/app/checkout/[step]/PaymentInfo.tsx
  src/app/checkout/[step]/PaymentProcess.tsx
  src/app/checkout/[step]/RejectedOrder.tsx
  src/app/checkout/[step]/ReviewOrder.tsx
  src/app/checkout/[step]/ShippingInfo.tsx
  src/app/checkout/[step]/page.tsx
  src/app/checkout/error.tsx
  src/app/checkout/layout.tsx
  src/app/checkout/page.tsx
  src/app/checkout/success.tsx
  src/app/product/[productId]/presentation/[presentationId]/page.tsx
  src/components/CardButton.tsx
  src/components/Cart/CartOverlay.tsx
  src/components/Product/ProductCard.tsx
  src/lib/validations/checkoutPaymentProcessSchema.ts
Labels: feature, help wanted

#54 Release 0.3.1
  package.json
  src/app/layout.tsx
  src/app/register/page.tsx
  src/components/User/ProfileLayout.tsx
Labels: bug
