Repository PharmaTechVe/ecommerce, pull requests merged in 2025-05, with the labels that each got.

#55 Feature: add breadcrumb to search page
  src/app/(shop)/page.tsx
  src/app/(shop)/product/[productId]/presentation/[presentationId]/page.tsx
  src/app/(shop)/search/page.tsx
  src/components/Breadcrumb.tsx
  src/components/CategoryCarousel.tsx
  src/components/SearchBar.tsx
  src/components/SidebarFilter.tsx
  src/lib/utils/images/Analgesicos.png
  src/lib/utils/images/Antibioticos.png
  src/lib/utils/images/Anticonvulsivo.png
  src/lib/utils/images/Antidiabetico.png
  src/lib/utils/images/Antiemetic.png
  src/lib/utils/images/Antigripales.png
  src/lib/utils/images/Antihipertensivo.png
Labels: feature

#58 Refactor Checkout Flow: Remove Context and Restore Order Creation
  .env.example
  package-lock.json
  package.json
  src/app/(shop)/checkout/CheckoutContext.tsx
  src/app/(shop)/checkout/[step]/PaymentInfo.tsx
  src/app/(shop)/checkout/[step]/PaymentProcess.tsx
  src/app/(shop)/checkout/[step]/ShippingInfo.tsx
  src/app/(shop)/checkout/[step]/page.tsx
  src/app/(shop)/checkout/error.tsx
  src/app/(shop)/checkout/layout.tsx
  src/app/(shop)/checkout/page.tsx
  src/app/(shop)/checkout/success.tsx
  src/app/(shop)/layout.tsx
  src/app/(shop)/order/[id]/page.tsx
  src/app/(shop)/user/order/[id]/detail/page.tsx
  src/components/Cart/Cart.tsx
  src/components/Cart/CartOverlay.tsx
  src/components/Cart/CartSummary.tsx
  src/components/GoogleMap/GoogleMap.tsx
  src/components/Navbar.tsx
  src/components/Order/Completed.tsx
  src/components/Order/DeliveryInfo.tsx
  src/components/Order/OrderSummary.tsx
  src/components/Order/PaymentProcess.tsx
  src/components/Order/ProductOrderSummary.tsx
  src/components/Order/RejectedOrder.tsx
  src/components/Order/ReviewOrder.tsx
  src/components/Order/WaitingApproval.tsx
  src/components/User/Order/UserOrderDetail.tsx
  src/context/CartContext.tsx
  src/lib/socket-url.ts
  src/lib/validations/checkoutPaymentProcessSchema.ts
Labels: feature, help wanted

#61 feature/notify-order-update-only-by-socket
  src/app/(shop)/order/[id]/page.tsx
Labels: feature

#66 hotfix/validate-event-type
  src/components/Navbar.tsx
Labels: bug

#64 Standardize validation schemas
  src/app/register/RegisterForm.tsx
  src/components/User/UserProfileForm.tsx
  src/lib/validations/checkoutPaymentProcessSchema.ts
  src/lib/validations/loginSchema.ts
  src/lib/validations/recoverPasswordSchema.ts
  src/lib/validations/registerSchema.ts
  src/lib/validations/updatePasswordSchema.ts
Labels: refactor

#65 Fix/ecom/notifications
  src/app/(shop)/layout.tsx
  src/app/(shop)/product/[productId]/presentation/[presentationId]/page.tsx
  src/components/Navbar.tsx
  src/components/User/NotificationBell.tsx
  src/components/User/NotificationList.tsx
  src/context/AuthContext.tsx
  src/lib/utils/constants/DateUtils.ts
Labels: fix

#67 Hotfix/ecom/order card fix
  package-lock.json
  package.json
  src/components/Badge.tsx
  src/components/Navbar.tsx
  src/components/Product/ProductCard.tsx
  src/components/User/NotificationBell.tsx
  src/components/User/NotificationList.tsx
  src/components/User/Order/UserOrderDetail.tsx
  src/components/User/Order/UserOrdertable.tsx
  src/lib/utils/helpers/useNotificationList.ts
Labels: fix
